def get_user_history(user_id: str):
    ...

def get_user_preferences(user_id: str):
    ...

def get_similar_users(user_id: str):
    ...

def get_similar_posts(post_id: str):
    ...

def get_posts_by_category(category: str | list[str]):
    ...

